### ISSUE TITLE
simplexml_load_string(): Entity: line 1: parser error : Space required after the Public Identifier

### ISSUE THREAD

**Issue by Roadirsh** [asifr/PHP-PubMed-API-Wrapper#9]
Hi,

The error come from the function PubMedAPI::load_xml_from_url. 
I got this error regularly on my website that use your class, it's really good so thank you, but I can't seems to figure this error out. I suppose that it is returning this error when the pubmed api is returning a 404 or any other webpage and not XML, maybe when the website is down, but how can I prevent simplexml_load_string to not failed if it is not and XML. 

Thanks.

**Comment by budflanksteak** [comment]
I performed the update to https on both lines for 'esearch' and 'efetch' (lines 42 & 43) but I am still getting an error from line 66: $this->count = int($xml)->Count;

I note that you didn't make any other changes to the file.  Does it still work for you?

Thanks

**Comment by Roadirsh** [comment]
Yes I did'nt get any other error since this change...

**Comment by budflanksteak** [comment]
Are there any specific settings required for the server to permit an SSL query? Doesn't seem to make sense that it works for you but not for me if I have already have made the appropriate changes to the query string to https.

**Comment by Roadirsh** [comment]
If you do var_dump($xml) juste before the ligne 66 what do you get ? @budflanksteak

**Comment by budflanksteak** [comment]
I get: bool(false)

I assume that means that $xml is not an object?

Adam E. Flanders, MD
Department of Radiology
Division of Neuroradiology/ENT
Thomas Jefferson University Hospital
Suite 1080B Main Building
132 S. Tenth St.
Philadelphia, PA  19107-5244

Voice: 215-955-2430
FAX: 215-923-1562
Page: 877-656-3642
EMAIL: adam.flanders@jefferson.edu
WEB: http://www.neuro.tju.edu

**Comment by Roadirsh** [comment]
Exact, so there must be an error in your search. Open a question on stackoverflow maybe ?
